### ISSUE TITLE
Unwanted prints to user when using filesystem methods

### ISSUE THREAD

**Issue by baloo1379** [jakubriegel/PUT_Eli_OS#19]
Kiedy używa się `filesystem.Files.fileExists()` drukuje on na ekran wynik sprawdzenia czy plik istnieje.
```java
[...]
if (Directories.getTargetDir().getFiles().fileExists(fileName)) {
[...]
```
![image](https://user-images.githubusercontent.com/25095808/50380262-322ecb80-0662-11e9-90b3-bdaa5c060356.png)

**Comment by SaronTetra** [comment]
Zmienione jakoś w trakcie
