### ISSUE TITLE
Forward slash in filesystem

### ISSUE THREAD

**Issue by baloo1379** [jakubriegel/PUT_Eli_OS#27]
zły ukośnik jest na plikach
![image](https://user-images.githubusercontent.com/25095808/50796906-65fd2880-12d3-11e9-92ad-f14bb2d9673b.png)

**Comment by SaronTetra** [comment]
Eh, głupie Windowsowe czepianie się 🥖

**Comment by baloo1379** [comment]
kole w oczy xd, jak chcesz to zrób. Chyba, że to jakaś prosta podmianka znaku w paru miejscach, to sam mogę.

**Comment by SaronTetra** [comment]
jak ci się chce to możesz zamienić / na \ u mnie
to chyba w directories będzie
zwykły replace nie powinien popsuć

**Comment by baloo1379** [comment]
[https://github.com/jakubriegel/PUT_Eli_OS/commit/b1e2597812dfa715b9ffc5fecefba8330d32695e](https://github.com/jakubriegel/PUT_Eli_OS/commit/b1e2597812dfa715b9ffc5fecefba8330d32695e)
Naprawione, zamykam.
